import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface Translations {
  [key: string]: {
    en: string;
    ar: string;
  };
}

const translations: Translations = {
  appTitle: { en: 'InsightFlow', ar: 'إنسيات فلو' },
  appTagline: { en: 'AI-Powered Data Analytics', ar: 'تحليل البيانات المعتمد على الذكاء الاصطناعي' },
  uploadFile: { en: 'Upload File', ar: 'رفع ملف' },
  clear: { en: 'Clear', ar: 'مسح' },
  dropDataTitle: { en: 'Drop your data here', ar: 'قم بإلقاء بياناتك هنا' },
  dropDataDesc: { en: 'Upload any Excel or CSV file to instantly generate a professional dashboard with AI insights.', ar: 'ارفع أي ملف Excel أو CSV لإنشاء لوحة تحكم احترافية فورية مع رؤى مدعومة بالذكاء الاصطناعي.' },
  excelBadge: { en: 'Excel (.xlsx)', ar: 'إكسل (.xlsx)' },
  csvBadge: { en: 'CSV (.csv)', ar: 'نصي (.csv)' },
  realTimeAnalysis: { en: 'Real-time analysis of {count} records', ar: 'تحليل فوري لـ {count} سجلات' },
  aiOptimized: { en: 'AI Optimized Layout', ar: 'تصميم محسن بالذكاء الاصطناعي' },
  searchPlaceholder: { en: 'Search records...', ar: 'بحث في السجلات...' },
  insightsTitle: { en: 'AI Business Intelligence', ar: 'ذكاء الأعمال الاصطناعي' },
  insightsDesc: { en: 'Deep analysis and strategic recommendations generated by Gemini.', ar: 'تحليل عميق وتوصيات استراتيجية تم إنشاؤها بواسطة Gemini.' },
  visualizations: { en: 'Visualizations', ar: 'التمثيلات البيانية' },
  rawData: { en: 'Raw Data', ar: 'البيانات الخام' },
  noResults: { en: 'No results found for your search.', ar: 'لم يتم العثور على نتائج لبحثك.' },
  errorAnalysisFailed: { en: 'AI analysis failed: {error}', ar: 'فشل تحليل الذكاء الاصطناعي: {error}' },
  errorNoApiKey: { en: 'GEMINI_API_KEY is not configured. Please check the Secrets panel.', ar: 'مفتاح GEMINI_API_KEY غير مهيأ. يرجى التحقق من لوحة الأسرار.' },
  avg: { en: 'Avg', ar: 'المتوسط' },
  rowsPerPage: { en: 'Rows per page', ar: 'عدد الصفوف في الصفحة' },
  of: { en: 'of', ar: 'من' },
  nightMode: { en: 'Night Mode', ar: 'وضع الليل' },
  dayMode: { en: 'Day Mode', ar: 'وضع النهار' },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, any>) => string;
  isRtl: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'ar';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string, params?: Record<string, any>) => {
    const translation = translations[key];
    if (!translation) return key;
    
    let text = translation[language];
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, String(v));
      });
    }
    return text;
  };

  const isRtl = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRtl }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};
